#!/bin/sh
#
# Start bigeye
#

start() {
	printf "Starting bigeye: "
	modprobe g_serial use_acm=0
	modprobe g_bigeye
	start-stop-daemon -b -S -q -m -p /var/run/bigeye-repeater.pid --exec /usr/bin/bigeye-repeater
	echo "OK"
}

stop() {
	printf "Stopping bigeye: "
	start-stop-daemon -K -q -p /var/run/bigeye-repeater.pid
	rmmod g_bigeye
	rmmod g_serial
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
